export const NEWS_LISTING_REFRESH = 'NEWS_LISTING_REFRESH';
export const NEWS_LISTING_LOADING = 'NEWS_LISTING_LOADING';
export const LOAD_MORE_NEWS_LISTING = 'LOAD_MORE_NEWS_LISTING';
export const NEWS_LISTING_CLEAR = 'NEWS_LISTING_CLEAR';
export const NEWS_LISTING = 'NEWS_LISTING';
